package main

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// DNSManager abstracts temporary DNS configuration for a VPN interface.
// Implementations must be safe to Remove even if Set was never called.
type DNSManager interface {
	// Set applies DNS servers and an optional search domain for device.
	Set(device string, servers []string, searchDomain string) error
	// Remove reverts the DNS configuration applied by Set.
	Remove(device string) error
}

// NewDNSManager returns the right DNS manager for the given backend name.
// "auto" probes the running system and picks the best available backend.
// Returns nil for "none" or when nothing suitable is detected.
func NewDNSManager(backend string) DNSManager {
	if backend == "auto" {
		backend = detectDNSBackend()
		if backend == "none" {
			slog.Info("no DNS manager detected, DNS will not be configured")
			return nil
		}
		slog.Info("detected DNS backend", "backend", backend)
	}
	switch backend {
	case "systemd-resolved":
		return &systemdResolvedDNS{}
	case "resolvconf":
		return &resolvconfDNS{}
	case "networkmanager":
		return &networkManagerDNS{}
	default:
		return nil
	}
}

// detectDNSBackend returns the best available DNS backend name.
func detectDNSBackend() string {
	active := func(unit string) bool {
		return exec.Command("systemctl", "is-active", "--quiet", unit).Run() == nil
	}
	if active("systemd-resolved") {
		return "systemd-resolved"
	}
	if _, err := exec.LookPath("resolvconf"); err == nil {
		return "resolvconf"
	}
	if active("NetworkManager") {
		return "networkmanager"
	}
	return "none"
}

// serversFromOptions extracts the ordered DNS server list from server options.
func serversFromOptions(opts map[string]string) []string {
	var out []string
	for _, key := range []string{"dns1", "dns2", "dns3"} {
		if v := opts[key]; v != "" {
			out = append(out, v)
		}
	}
	return out
}

// ── systemd-resolved ──────────────────────────────────────────────────────────
// Uses resolvectl to set per-link DNS. Changes are automatically reverted
// when the interface disappears, and also reverted explicitly on Remove.

type systemdResolvedDNS struct{}

func (d *systemdResolvedDNS) Set(device string, servers []string, searchDomain string) error {
	if len(servers) > 0 {
		args := append([]string{"dns", device}, servers...)
		if out, err := exec.Command("resolvectl", args...).CombinedOutput(); err != nil {
			return fmt.Errorf("resolvectl dns: %w: %s", err, out)
		}
	}
	if searchDomain != "" {
		if out, err := exec.Command("resolvectl", "domain", device, searchDomain).CombinedOutput(); err != nil {
			return fmt.Errorf("resolvectl domain: %w: %s", err, out)
		}
	}
	// Keep this interface from becoming the system-wide default DNS route
	// so only traffic destined for the VPN's domain goes through it (split DNS).
	exec.Command("resolvectl", "default-route", device, "no").Run()
	return nil
}

func (d *systemdResolvedDNS) Remove(device string) error {
	out, err := exec.Command("resolvectl", "revert", device).CombinedOutput()
	if err != nil {
		return fmt.Errorf("resolvectl revert: %w: %s", err, out)
	}
	return nil
}

// ── resolvconf ────────────────────────────────────────────────────────────────
// Pipes a resolv.conf fragment to the resolvconf(8) utility.
// The fragment is removed on Remove, restoring the previous configuration.

type resolvconfDNS struct{}

func (d *resolvconfDNS) Set(device string, servers []string, searchDomain string) error {
	var lines []string
	lines = append(lines, "# generated by nxbender for "+device)
	for _, ns := range servers {
		lines = append(lines, "nameserver "+ns)
	}
	if searchDomain != "" {
		lines = append(lines, "search "+searchDomain)
	}

	cmd := exec.Command("resolvconf", "-a", device)
	cmd.Stdin = strings.NewReader(strings.Join(lines, "\n") + "\n")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("resolvconf -a: %w: %s", err, out)
	}
	return nil
}

func (d *resolvconfDNS) Remove(device string) error {
	out, err := exec.Command("resolvconf", "-f", "-d", device).CombinedOutput()
	if err != nil {
		return fmt.Errorf("resolvconf -d: %w: %s", err, out)
	}
	return nil
}

// ── NetworkManager ────────────────────────────────────────────────────────────
// Writes a dnsmasq split-DNS config fragment and signals NM to reload.
// Requires dns=dnsmasq in [main] of NetworkManager.conf.
// The file is removed and NM is reloaded on Remove.

const nmDnsmasqConf = "/etc/NetworkManager/dnsmasq.d/nxbender.conf"

type networkManagerDNS struct{}

func (d *networkManagerDNS) Set(device string, servers []string, searchDomain string) error {
	if len(servers) == 0 {
		return nil
	}

	var lines []string
	lines = append(lines, "# generated by nxbender — removed on VPN disconnect")
	for _, ns := range servers {
		if searchDomain != "" {
			lines = append(lines, fmt.Sprintf("server=/%s/%s", searchDomain, ns))
		}
		lines = append(lines, "server="+ns)
	}

	if err := os.MkdirAll(filepath.Dir(nmDnsmasqConf), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(nmDnsmasqConf, []byte(strings.Join(lines, "\n")+"\n"), 0644); err != nil {
		return err
	}
	if out, err := exec.Command("nmcli", "general", "reload", "dns-full").CombinedOutput(); err != nil {
		slog.Warn("nmcli reload dns-full failed", "output", strings.TrimSpace(string(out)))
	}
	return nil
}

func (d *networkManagerDNS) Remove(_ string) error {
	if err := os.Remove(nmDnsmasqConf); err != nil && !os.IsNotExist(err) {
		return err
	}
	if out, err := exec.Command("nmcli", "general", "reload", "dns-full").CombinedOutput(); err != nil {
		slog.Warn("nmcli reload dns-full failed", "output", strings.TrimSpace(string(out)))
	}
	return nil
}
